fix: calculate valid widths by virtcol()
lukas-reineke/virt-column.nvim pull request #37
Opened 2023-07-15 03:54 UTC by delphinus

This fixes 2 problems.

## 1. consider Tab's validly

The current build calculates line widths with replacing Tab `\t` into `'tabstop'` count of spaces.

https://github.com/lukas-reineke/virt-column.nvim/blob/93b40ea038f676f5a72d7d1f2336fe7b051fc0ce/lua/virt-column/init.lua#L79-L80

We gets wrong widths by this logic. This is because the logic always calculates the width of `\t` into the `'tabtop'` value. I fixed this by using `virtcol()`.

```vim
" Below shows tab string by >------- string
" set tabstop=8
foo_bars>-------foo  " --> it calculates the width: 19 -- This is correct.
foo_bar_foo>----foo  " --> it calculates the width: 22 -- This is wrong! The correct value is 19.
```

## 2. consider inline virtual texts

Now Neovim has [inline virtual texts][1] and it can insert texts between chars in lines. This problem is also solved by `virtcol()`.

[1]: https://github.com/neovim/neovim/pull/20130

FYI: With such inline texts, `'cursorcolumn'` itself does not move. See discussions in https://github.com/neovim/neovim/pull/24090.

2023-07-18 02:45 UTC, lukas-reineke requested changes
nice thanks!

Just one small comment

2023-07-18 02:45 UTC, lukas-reineke commented on lua/virt-column/init.lua
> +    for i = 1, vim.fn.line "$", 1 do
```suggestion
    for i = 1, vim.api.nvim_buf_line_count(bufnr), 1 do
```

This can be a lua function

2023-07-18 06:05 UTC, delphinus commented on lua/virt-column/init.lua
> +    for i = 1, vim.fn.line "$", 1 do
Good catch 👍🏼 I fixed this.

2023-07-24 02:23 UTC, lukas-reineke approved these changes
:rocket:

2023-07-24 02:24 UTC, merged