fix: replace deprecated vim.tbl_flatten with vim.iter
lukas-reineke/virt-column.nvim pull request #47
Opened 2024-11-05 09:40 UTC by topaxi

Supersedes #43, as #43 broke the column for me.

If backwards compatibility is a concern, I'd be happy to add a code path which feature detects `vim.iter`.

2024-11-11 11:12 UTC, lukas-reineke requested changes

2024-11-11 11:12 UTC, lukas-reineke commented on lua/virt-column/utils.lua
> +    return vim.iter({ ... }):flatten():totable()
Thanks, but yes let's keep this backwards compatible please.

This should be fine.

```suggestion
    ---@diagnostic disable-next-line: deprecated
    return vim.iter and vim.iter({ ... }):flatten():totable() or vim.tbl_flatten { ... }
```

2024-11-11 20:31 UTC, topaxi commented
Updated as suggested, thank you :blush:

2024-11-12 02:51 UTC, lukas-reineke approved these changes
Thank you

2024-11-12 02:52 UTC, merged